<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="smokeTest"
           tests="4"
           failures="1"
           errors="0"
           skipped="0"
           time="7.307">
  <properties />
            <testcase name="testDrawings_amount" time="3.836" classname="smoke.b.qccr.Tikuan_NormalTest">
                <failure type="java.lang.AssertionError"
                  message="提款金额不足 expected [true] but found [false]"
              >
<![CDATA[java.lang.AssertionError: 提款金额不足 expected [true] but found [false]
  org.testng.Assert.fail(Assert.java:94)
  org.testng.Assert.failNotEquals(Assert.java:494)
  org.testng.Assert.assertTrue(Assert.java:42)
  com.common.ats.Assert.AtsAssertUtils.assertTrue(AtsAssertUtils.java:50)
  smoke.b.qccr.Tikuan_NormalTest.testDrawings_amount(Tikuan_NormalTest.java:66)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
  java.lang.reflect.Method.invoke(Unknown Source)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
  org.testng.TestRunner.privateRun(TestRunner.java:767)
  org.testng.TestRunner.run(TestRunner.java:617)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
  org.testng.SuiteRunner.run(SuiteRunner.java:240)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
  org.testng.TestNG.run(TestNG.java:1057)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="testOrder_numbers" time="0.067" classname="smoke.b.qccr.Tikuan_NormalTest" />
                <testcase name="testOrder_amount" time="0.066" classname="smoke.b.qccr.Tikuan_NormalTest" />
                <testcase name="testReward_amount" time="3.338" classname="smoke.b.qccr.Tikuan_NormalTest" />
      
</testsuite>
